# Generated by Django 4.2.18 on 2025-01-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base',
            old_name='Base',
            new_name='base',
        ),
        migrations.AddField(
            model_name='base',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
