# Generated by Django 4.2.18 on 2025-01-31 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('county', models.CharField(choices=[('Antrim', 'Antrim'), ('Armagh', 'Armagh'), ('Carlow', 'Carlow'), ('Cavan', 'Cavan'), ('Clare', 'Clare'), ('Cork', 'Cork'), ('Derry', 'Derry'), ('Donegal', 'Donegal'), ('Down', 'Down'), ('Dublin', 'Dublin'), ('Fermanagh', 'Fermanagh'), ('Galway', 'Galway'), ('Kerry', 'Kerry'), ('Kildare', 'Kildare'), ('Kilkenny', 'Kilkenny'), ('Laois', 'Laois'), ('Leitrim', 'Leitrim'), ('Limerick', 'Limerick'), ('Longford', 'Longford'), ('Louth', 'Louth'), ('Mayo', 'Mayo'), ('Meath', 'Meath'), ('Monaghan', 'Monaghan'), ('Offaly', 'Offaly'), ('Roscommon', 'Roscommon'), ('Sligo', 'Sligo'), ('Tipperary', 'Tipperary'), ('Tyrone', 'Tyrone'), ('Waterford', 'Waterford'), ('Westmeath', 'Westmeath'), ('Wexford', 'Wexford'), ('Wicklow', 'Wicklow')], max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('eircode', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='base',
            name='base',
            field=models.CharField(default='Regular', max_length=50),
        ),
        migrations.AlterField(
            model_name='base',
            name='price',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='cheese',
            field=models.CharField(default='Mozarella', max_length=50),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='price',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='crust',
            name='crust',
            field=models.CharField(default='Normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='crust',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping',
            field=models.ManyToManyField(blank=True, default=None, to='main.topping'),
        ),
        migrations.AlterField(
            model_name='size',
            name='price',
            field=models.FloatField(default=11.5),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.address'),
        ),
    ]
