# Generated by Django 4.2.18 on 2025-02-11 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_orders_pizza_cart_orders_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardHolder', models.CharField(max_length=50)),
                ('cardNumber', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Enter a valid 16-digit card number.')])),
                ('expiration_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expiration_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2025), django.core.validators.MaxValueValidator(2030)])),
                ('cvv', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
    ]
