# Generated by Django 4.2.18 on 2025-02-12 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_payment_expiration_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiration_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2025), django.core.validators.MaxValueValidator(2035)]),
        ),
    ]
