# Generated by Django 5.1.3 on 2025-02-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_payment_cardnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pizzas',
            field=models.ManyToManyField(to='main.pizza'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
    ]
